---
# Defines tasks applicable for postgreSQL

- name: Install Postgres
  apt: pkg={{ item }} state=installed
  with_items:
    - postgresql
    - python-psycopg2
  tags:
    - dependencies

- name: Set password for PostgreSQL admin user
  become: true
  become_user: postgres
  postgresql_user: name={{ db_admin_username }} password={{ db_admin_password }} encrypted=yes
